import type { LucideIcon } from 'lucide-react-native';

export type DataMethodId = 'upload';

export type BiologicalSex = 'female' | 'male' | 'other' | 'prefer-not-say' | string;

export interface UserProfile {
  name?: string;
  age?: number;
  sex?: BiologicalSex;
  weightKg?: number;
  heightCm?: number;
  restingHeartRate?: number;
  waistCm?: number;
  sleepDurationHrs?: number;
  preferredLanguage?: 'en' | 'ro';
  dataMethods: DataMethodId[];
  primaryInterests: string[];
  medicalConditions: string[];
  medications?: string[];
  physicalConcernIds: string[];
  onboardingMessages?: { role: 'user' | 'assistant'; content: string }[];
  /** The user story derived from onboarding, generated by the LLM when onboarding is complete */
  onboardingUserStory?: {
    asA: string;
    iWantTo: string;
    soThat: string;
    fullStory: string;
  };
  completedAt: string;
}

/** habitId -> questionId -> answer (string for single/number, string[] for multi). */
export type GoalDetails = Record<string, Record<string, string | string[]>>;

export interface SexOption {
  id: BiologicalSex;
  label: string;
}

export interface DataMethodOption {
  id: DataMethodId;
  title: string;
  description: string;
  icon: LucideIcon;
  enabled?: boolean;
}

export interface HabitOption {
  id: string;
  title: string;
  time: string;
  reason: string;
}
